# This file was generated by Hastega.Generator.Interface
defmodule HastegaNif do
  @on_load :load_nifs

  def load_nifs do
    :erlang.load_nif('./priv/libnif', 0)
  end

  def map_mult(_arg1), do: raise "NIF map_mult/1 not implemented"
  def map_plus(_arg1), do: raise "NIF map_plus/1 not implemented"

end
